import fs from "node:fs/promises";
import path from "node:path";
import { getUsername } from "./username";

async function pathExists(target: string) {
  try {
    await fs.access(target);
    return true;
  } catch {
    return false;
  }
}

function starterPrototypesFile() {
  return `export type Prototype = {
  slug: string;
  title: string;
  description?: string;
  date: string;
};

export const prototypes: Prototype[] = [
];
`;
}

function claudeLocalContent(username: string, relativeUserDir: string, isRegistered: boolean) {
  const registrationNote = isRegistered
    ? ""
    : `\n## Not yet on the homepage\n\nThis namespace isn't registered in \`src/app/registry.ts\` yet, so its prototypes won't appear on the homepage list. Add it to the \`authors\` array there (a one-time, shared-file edit) when ready.\n`;

  return `# CLAUDE.local.md

Auto-generated by \`scripts/setup-local.ts\` on \`bun dev\` — regenerated every run, not committed to git. Don't hand-edit; changes will be overwritten.

## Who you are

- Local developer: \`${username}\` (derived from \`git config user.name\`, falling back to the OS username)
- Your namespace: \`${relativeUserDir}/\`

## Scope

Stay inside \`${relativeUserDir}/\` when working on this developer's prototypes:

- Create, edit, and delete files only within \`${relativeUserDir}/\`.
- Do not modify any other developer's folder under \`src/app/\` (e.g. other plain top-level folders that aren't \`(root)\`, \`(nds)\`, \`(templates)\`, \`api\`, or shared infra).
- Shared app infrastructure (\`src/app/(root)/\`, \`src/app/(nds)/\`, \`src/app/(templates)/\`, \`src/components/\`, \`src/icons/\`, \`src/app/api/\`, \`src/app/registry.ts\`, \`scripts/\`) is off-limits unless the user explicitly asks for a change there.
- To scaffold a new prototype for this developer, use the \`create-prototype\` skill or run \`bun run create-prototype -- --name "..."\` — don't hand-write \`page.tsx\` or edit \`prototypes.ts\` directly.
${registrationNote}`;
}

async function main() {
  const cwd = process.cwd();
  const username = getUsername();
  const userDir = path.join(cwd, "src", "app", username);
  const prototypesFile = path.join(userDir, "prototypes.ts");

  const isNewNamespace = !(await pathExists(userDir));
  await fs.mkdir(userDir, { recursive: true });
  if (!(await pathExists(prototypesFile))) {
    await fs.writeFile(prototypesFile, starterPrototypesFile(), "utf8");
  }

  const registrySource = await fs.readFile(
    path.join(cwd, "src", "app", "registry.ts"),
    "utf8"
  );
  const isRegistered = registrySource.includes(`"${username}"`);

  const relativeUserDir = path.relative(cwd, userDir);
  await fs.writeFile(
    path.join(cwd, "CLAUDE.local.md"),
    claudeLocalContent(username, relativeUserDir, isRegistered),
    "utf8"
  );

  console.log(
    `[setup-local] ${username} -> ${relativeUserDir}/${isNewNamespace ? " (created)" : ""}`
  );
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
